### ISSUE TITLE
[meta] Refactor and make it a client side app

### ISSUE THREAD

**Issue by bfabio** [italia/developers-italia-onboarding#204]
The app is now a server side node application, but we can refactor it into a static client side app, plus a couple of support FaaS API endpoints

- [ ] Pick a client side framework
- [ ] Implement the API call that generate the token and sent the confirmation email
- [ ] Implement the API call that validate the token
- [ ] Use developers-italia-api with no local state (#203)
